name: Terraform CI/CD

on:
  pull_request:
    paths:
      - 'modules/**'
      - 'environments/**'
  push:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'environments/**'

jobs:
  terraform:
    name: 'Terraform Validate & Plan'
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan (Dev)
        working-directory: environments/dev
        run: terraform plan -out=dev.plan

      - name: Upload plan file
        uses: actions/upload-artifact@v3
        with:
          name: dev-plan
          path: environments/dev/dev.plan

      # Repeat for prod environment
      - name: Terraform Init (Prod)
        working-directory: environments/prod
        run: terraform init -input=false

      - name: Terraform Validate (Prod)
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform Plan (Prod)
        working-directory: environments/prod
        run: terraform plan -out=prod.plan

      - name: Upload plan file (Prod)
        uses: actions/upload-artifact@v3
        with:
          name: prod-plan
          path: environments/prod/prod.plan
