name: Terraform CI/CD

on:
  workflow_dispatch:
  
permissions:
     id-token: write
     issues: write
     pull-requests: write
     contents: read

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      #ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -input=false

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          

      - name: Terraform Init
        run: terraform -chdir=Terraform/maim/nonprod init -upgrade -reconfigure -backend-config ../../environments/nonprod/backend.conf

    

      - name: Terraform Plan (Dev)
        id: tf-plan
        run: |
         export exitcode=0
         terraform -chdir=Terraform/main/nonprod plan -var-file ../../environments/nonprod/terraform.tfcars -detailed-exitcode -no-color -out tfplan || export exitcode=$?
         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

         if [ $exitcode -eq 1]; then
           echo Terraform plan failed!
           exit 1
         else
          exit 0
         fi 

      - name: Upload plan file
        uses: actions/upload-artifact@v3
        with:
          name: dev-plan
          path: environments/dev/dev.plan

      # # Repeat for prod environment
      # - name: Terraform Init (Prod)
      #   working-directory: environments/prod
      #   run: terraform init -input=false

      # - name: Terraform Validate (Prod)
      #   working-directory: environments/prod
      #   run: terraform validate

      # - name: Terraform Plan (Prod)
      #   working-directory: environments/prod
      #   run: terraform plan -out=prod.plan

      # - name: Upload plan file (Prod)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: prod-plan
      #     path: environments/prod/prod.plan
